# Generated by Django 4.0.5 on 2022-07-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='title',
            new_name='job_title',
        ),
    ]
