# Generated by Django 4.0.5 on 2022-07-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='agree',
            field=models.BooleanField(default=False),
        ),
    ]
